### ISSUE TITLE
Output in reverse order.

### ISSUE THREAD

**Issue by m-ou-se** [de-vri-es/fizzbuzz-error#1]
`fizzbuzz_to<3>` produces `result<fizz, n<2>, n<1>>`, instead of `result<n<1>, n<2>, fizz>`.

**Comment by de-vri-es** [comment]
Fixed in 7ba68efec0313ee99dfaefa8678049bfb699a149. Can you confirm and close?

**Comment by m-ou-se** [comment]
Confirmed.
